import Navigation from "@/components/Navigation";
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className="w-full h-full"
      >
        <Navigation />
        <div className="flex justify-center">
          <div className="w-[800px] h-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
